### ISSUE TITLE
java process stays at 100% activity

### ISSUE THREAD

**Issue by ashleycoker** [stisti/jenkins-app#21]
After running a few jobs, intermittently, the java process stays at 100% in Activity Monitor and the jenkins server no longer responds (UI is dead too).

This seemed to happen after I installed the ruby rvm manager and multiple versions of ruby, but this could be nothing to do with it.  All was fine before then though.

I can restart Jenkins by killing the out of control java process, killing the jenkins app (force quit) and another java process spawns from nowhere - kill that, wait until it does not load another one, then restart the Jenkins app. 

This is now happening every few clicks around the web UI of jenkins, i.e. the java process loses control and I have to force quit as described above.  It has made the solution unworkable.

Installing Jenkins via other means on the same machine does not seem to cause this issue, although I have not tested in anger as I have a load of permissions issues preventing me running any of my jobs now!  the very reason I moved to your solution!  ahhh!

**Comment by stisti** [comment]
A new Jenkins java process is started automatically because Jenkins.app submits a job named org.jenkins-ci.jenkins to launchd. If you want to get rid of it, run 

```
launchctl remove org.jenkins-ci.jenkins
```

I cannot immediately think of any reason why Jenkins.app would make Jenkins run in a busy loop. I need more information.
- What other ways of installing Jenkins have you tried?
- Did you try just running: java -jar ~/Library/Caches/org.jenkins-ci.jenkins/jenkins.war (This is what Jenkins.app essentially does)
- Have you opened the system log? (by running Console.app or peeking into /var/log/system.log) Any messages there from Jenkins.app or the Jenkins java process?
- If nothing else helps, try the java troubleshooting tools (http://docs.oracle.com/javase/7/docs/technotes/tools/index.html#troubleshoot) and/or dtruss or sample on the java process.

One thing that comes to mind: Maybe you run out of memory in Java? That can cause difficult-to-debug problems in Java. But it should be visible in the system log. Or right there on the Terminal if you execute Jenkins yourself.

HTH,

Sami

**Comment by vzqwer** [comment]
I faced with the same problem. The java process loads 100% CPU and web UI stops to respond. 
It starts after "Over-the-Air Ad Hoc Deployment Plugin For iOS" plugin instaled. This plugin also require "ruby-runtime" plugin. Unistalling both solves the problem.
Where can I find logs or something else to find the reason?

**Comment by KrauseFx** [comment]
I'm experiencing the exact same problem. Is that caused by Jenkins itself or the "Jenkins App"?

**Comment by KrauseFx** [comment]
In my console I find the following logs that might help debugging this issue:

This line occurs every minute:
29/03/14 13:22:26,372 Jenkins.app[58729]: Error in busy check: The command exited with a non-zero status. (22)

Killing the jenkins or java process does not solve it, I have to restart the whole computer.

Other lines that occurred only once:
28/03/14 16:58:18,534 spindump[54777]: Saved cpu_resource.spin report for jenkins.war version ??? (???) to /Library/Logs/DiagnosticReports/jenkins.war_2014-03-28-165818_Felixs-Mac-Pro.cpu_resource.spin
28/03/14 17:00:03,377 Finder[696]: AppleEvents/sandbox: Returning errAEPrivilegeError/-10004 and denying dispatch of event syso/nfo4 from process 'Jenkins'/0x0-0x84084, pid=54857, because it is not entitled to send an AppleEvent to this process.
28/03/14 17:00:03,383 Jenkins.app[54859]: Current version: 56
28/03/14 17:01:19,906 Jenkins.app[54914]: Jenkins cache folder is Mac:Users:felixkrause:Library:Caches:org.jenkins-ci.jenkins:
28/03/14 17:01:19,919 Jenkins.app[54916]: jenkins.war exists at /Users/felixkrause/Library/Caches/org.jenkins-ci.jenkins/jenkins.war

**Comment by twhq** [comment]
I encountered this same issue with "Jenkins App" so I switched over to a traditional Jenkins installation and it's still happening. Appears to be a problem with Jenkins itself on the Mac.

**Comment by KrauseFx** [comment]
@tompowered Thanks for your answer. That would have been my next step. Have you found any solution yet? 
I'm using Jenkins to do the following:
- Execute ruby scripts
- Control Android emulators
- Build and upload iOS and Android projects.

**Comment by twhq** [comment]
I have not found a solution, or a cause.

There's a handful of bugs in Jenkins' bugtracker for this issue but no resolutions:

https://issues.jenkins-ci.org/browse/JENKINS-22170

**Comment by stisti** [comment]
Thanks for the pointer! I was fairly certain Jenkins.app cannot cause it because it just launches the Java process to run under launchd. If you want to verify that, you can run Jenkins yourself in a terminal window by typing: 

```
java -jar ~/Library/Caches/org.jenkins-ci.jenkins/jenkins.war
```
